In [ ]:
from google.colab import files
file=files.upload()

Saving Placement_Data_Full_Class.csv to Placement_Data_Full_Class.csv

In [ ]:
import pandas as pd

df = pd.read_csv("Placement_Data_Full_Class.csv")
df.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [ ]:
df.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [ ]:
# Check missing values in each column
df.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [ ]:
# Fill missing salary values (students not placed → no salary)
df['salary'] = df['salary'].fillna(0)

In [ ]:
# Remove duplicate records (if any)
df.drop_duplicates(inplace=True)

In [ ]:
# Clean text columns (remove spaces and standardize format)
df['gender'] = df['gender'].str.strip().str.upper()
df['workex'] = df['workex'].str.strip().str.upper()
df['status'] = df['status'].str.strip().str.capitalize()
df['specialisation'] = df['specialisation'].str.strip()

In [ ]:
# Convert salary column to integer type
df['salary'] = df['salary'].astype(int)

In [ ]:
# Create a new column to categorize salary levels
df['salary_category'] = df['salary'].apply(lambda x:
    'No Salary' if x == 0 else
    'Low' if x < 300000 else
    'Medium' if x < 600000 else
    'High'
)

In [ ]:
# Save cleaned dataset to CSV file
df.to_csv("placement_cleaned_dataset.csv", index=False)

In [ ]:
#Downloading Cleaned data
from google.colab import files
files.download("placement_cleaned_dataset.csv")